# Generated by Django 5.2.7 on 2026-06-28 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_bookings'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='bus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.bus'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='seat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.seat'),
        ),
    ]
